version: 2

builds:
- id: acl
  main: ./main.go
  binary: acl
  ldflags:
  - -s -w -X "github.com/tsuru/acl-api/api/version.Version={{ .Tag }}"
  env:
  - CGO_ENABLED=0
  goos:
  - darwin
  - linux
  - windows
  goarch:
  - amd64
  - 386
  - arm64
  ignore:
  - goos: darwin
    goarch: 386
  - goos: windows
    goarch: arm64

archives:
- id: acl
  ids:
  - acl
  name_template: >-
    acl_{{ .Version }}_
    {{- if eq .Os "darwin" -}}
      Darwin
    {{- else if eq .Os "linux" -}}
      Linux
    {{- else if eq .Os "windows" -}}
      Windows
    {{- else -}}
      {{ .Os }}
    {{- end }}_
    {{- if eq .Arch "amd64" -}}
      x86_64
    {{- else if eq .Arch "386" -}}
      i386
    {{- else -}}
      {{- .Arch }}
    {{- end }}
  format_overrides:
  - goos: windows
    formats: zip
  files:
  - LICENSE

checksum:
  name_template: "checksums.txt"

release:
  prerelease: auto
  extra_files:
    - glob: ./manifest.json
